const fs = require('fs');
const path = require('path');

// Try to load .env.local if it exists (for local development)
const localEnvPath = path.join(__dirname, '..', '.env.local');
if (fs.existsSync(localEnvPath)) {
  const envContent = fs.readFileSync(localEnvPath, 'utf8');
  envContent.split('\n').forEach(line => {
    if (line.trim() && !line.startsWith('#')) {
      const [key, value] = line.split('=');
      if (key && value) {
        process.env[key.trim()] = value.trim();
      }
    }
  });
}

// Read configuration from environment variables
// 如果未设置, 留空字符串, 与客户端 isConfigured() 判断保持一致
const config = {
  SUPABASE_URL: (process.env.SUPABASE_URL || '').trim(),
  SUPABASE_ANON_KEY: (process.env.SUPABASE_ANON_KEY || '').trim()
};

// 验证 URL 格式 (避免写入了非空但无意义的值)
function isValidUrl(s) {
  return s && s.startsWith('https://') && s.includes('.');
}

if (config.SUPABASE_URL && !isValidUrl(config.SUPABASE_URL)) {
  console.warn('⚠️  SUPABASE_URL 看起来不是合法 URL, 已忽略');
  config.SUPABASE_URL = '';
}

if (config.SUPABASE_ANON_KEY && config.SUPABASE_ANON_KEY.length < 20) {
  console.warn('⚠️  SUPABASE_ANON_KEY 长度过短, 已忽略');
  config.SUPABASE_ANON_KEY = '';
}

// Generate the config.js file content
const configContent = `// This file is auto-generated by scripts/build-config.js
// For Vercel deployment, set SUPABASE_URL and SUPABASE_ANON_KEY in project settings
window.VEX_CONFIG = ${JSON.stringify(config, null, 2)};
`;

// Write to src/js/config.js
const outputPath = path.join(__dirname, '..', 'src', 'js', 'config.js');
fs.writeFileSync(outputPath, configContent, 'utf8');

const hasUrl = config.SUPABASE_URL.length > 0;
const hasKey = config.SUPABASE_ANON_KEY.length > 0;
console.log('✅ Configuration file generated:', outputPath);
console.log('   SUPABASE_URL:', hasUrl ? '(set)' : '(empty)');
console.log('   SUPABASE_ANON_KEY:', hasKey ? '(set)' : '(empty)');
if (!hasUrl || !hasKey) {
  console.log('');
  console.log('💡 提示: 请在以下位置之一设置 Supabase 配置:');
  console.log('   - Vercel 项目 Settings → Environment Variables');
  console.log('   - 项目根目录的 .env.local 文件 (本地开发)');
}
